---
abstract: 'Simplified data plotting with SVG'
author:
  - 'Gene Boggs <gene@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300016, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: SVG-Graph-Kit
requires:
  SVG::Graph: 0
  SVG::Graph::Data: 0
  SVG::Graph::Data::Datum: 0
  base: 0
  strict: 0
  warnings: 0
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=SVG-Graph-Kit
  repository: https://github.com/ology/Math/tree/master/SVG-Graph-Kit
version: 0.0102
