#!/usr/bin/perl
use strict;
use warnings;
use lib '/Users/gene/bin/SVG-Graph-Kit/lib';
use SVG::Graph::Kit;
my $n = shift || 20;
@ARGV = '/Users/gene/bin/math/primes/0000002_611953.txt';
my $i = 0;
my @x = ();
push @x, $_ while ($_ = <>) =~ s/\D//g && ++$i <= $n;
$i = 0;
my @d = map { [ ++$i, $n * $_ / $x[-1] ] } @x;
my $g = SVG::Graph::Kit->new(
    _axis => {
        grid => 1,
        # Constant x, Constant y:
        x => $n, y => $x[-1],
        xlabels => [ 0 .. $n ],
        ylabels => [ 0 .. $x[-1] ],
        # Constant x, Scaled y:
#        m => 1, n => $n, s => 10,
#        xlabels => [ 0 .. $n ],
#        ylabels => [ 0, map { int $_ * $x[-1] / $n } 1 .. $n ],
    },
    _items => [
        { data => \@d, line => { stroke => 'yellow' } },
        { data => \@d, scatter => { stroke => 'blue' } },
    ],
);
print $g->draw;
